@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/post/comments/6366504370b2f816c72fb67d
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/6366504370b2f816c72fb67d
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/6366504370b2f816c72fb67d/636f92bc1aad6e957e7c7046

Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "63552ac989155a6d0f67d2af",
  "postId": "6366504370b2f816c72fb67d",
  "comment": "This Is My second Comment",
  "profilePicture": "<cloudinary-user-profile-picture-url>"
}
